### ISSUE TITLE
Suggestions to the unity 32 -> 64 bit guide

### ISSUE THREAD

**Issue by M0REKZ** [boggydigital/mac-gaming-guides#1]
Hi, Nice improving for my guide, however there are some things i would like to add/change:

- [x]  Change the Frameworks folder copy to directly copying the Mono dylibs, because sometimes unityplayer would look for libraries that noob people put here, and if you copy the frameworks folder you may delete these.

- [x] Sometimes you wouldnt find mac unity editor packages, but also sometimes Linux and windows ones includes a _mac unity player_, i dont know on what cases, but i remember one time taking one from a linux installer.

- [x] When you try to debug the app, sometimes will epic launch steam drm (reseting the app) and you cant see terminal output, so is better so use the -logfile flag

Thanks for reading :D

EDIT: Added later:

- [x] Make people better to check if the unityplayer that is being used for updating is the right version, i remember on the past downloading something like unity 4.x.x or 3.x.x and it coming with a 20xx.x.x incompatible player for a unknown reason, just in case 👍

- [x] #2

**Comment by boggydigital** [comment]
All great suggestions! I'll incorporate soon

**Comment by boggydigital** [comment]
@M0REKZ please check out https://github.com/boggydigital/mac-gaming-guides/commit/4e76a076eda63283eb270811fe4fe3f1b4466805 - I believe I've addressed the feedback

**Comment by M0REKZ** [comment]
Yay, now is better, thanks

But i realized i epic forgot something, sorry lol

* Make the people better to check if the unityplayer that is being used for updating is the right version, i remember on the past downloading something like unity 4.x.x or 3.x.x and it coming with a 2019 incompatible player for a unknown reason, just in case 👍

* Check the third party libraries for the case they are 32bits only with the `file` command

Thats all, ill close the issue after this, Thanks

**Comment by boggydigital** [comment]
Fascinating, didn't know that could happen - how one would go to check whether downloaded player is the right version? I've no idea and always assumed there is 1:1 match.

**Comment by M0REKZ** [comment]
> Fascinating, didn't know that could happen - how one would go to check whether downloaded player is the right version? I've no idea and always assumed there is 1:1 match.

Yeah, its possible, but anyways it looks like they fixed it (im not sure, but just in case) the more "normal way" to recognize it would be finding arm64 players on a unity 4.x.x package and a source folder with a xcode project, the other way i use too to verify this (but at this point it may be unnecessary) is open UnityPlayer bin (or Unityplayer.dylib) with textedit and look for the version with command + F :P (yeah, textedit lol, maybe there is a better way for terminal guys)

**Comment by boggydigital** [comment]
That makes sense - please check out https://github.com/boggydigital/mac-gaming-guides/commit/b29de7ef239cb98e234506260e94af6cfd992185 where I've outlined this process

**Comment by M0REKZ** [comment]
>If you're getting multiple lines with that version - it's likely that you've got a wrong version and need to re-download the correct one: see [Determine Unity version](https://github.com/boggydigital/mac-gaming-guides/blob/main/common/unity-32-to-64.md#determine-unity-version) and [Download Unity](https://github.com/boggydigital/mac-gaming-guides/blob/main/common/unity-32-to-64.md#download-unity).

what, im confused, wouldn't it be something like that?: 

> if you find lines saying the exact same version you put on command, you downloaded the right one

**Comment by boggydigital** [comment]
Great catch - that's what I get for rushing changes on the go, should be "If you're NOT getting multiple lines with that version - it's likely that you've got a wrong version". I rework to a better phrase later tonight!

**Comment by boggydigital** [comment]
I like the todo list format! Here is the Unity player version check: https://github.com/boggydigital/mac-gaming-guides/commit/cb6cccd92cbe6615f937e945b0b97dd3f710d3dd. Let me convert libraries into a separate issue as that seems like a larger topic that needs to be researched more
