### ISSUE TITLE
Clarify path for standalone player version

### ISSUE THREAD

**Issue by Browun** [boggydigital/mac-gaming-guides#7]
Following the example path for the step [_Validating that you've downloaded the correct standalone player version_](https://github.com/boggydigital/mac-gaming-guides/blob/main/common/unity-porting.md#validating-that-youve-downloaded-the-correct-standalone-player-version) led me to have some confusion about the correct location to run the verification command, since there are two `Unity.app` resources.

My suggestion would be to update [this line](https://github.com/boggydigital/mac-gaming-guides/blob/3b0b352bd7c10b376cd2883be98a37078a87cb84/common/unity-porting.md?plain=1#L329) to be:

```markdown
- Navigate to the location of the player you previously discovered above, under the path `Contents/PlaybackEngines/MacStandaloneSupport/Variations` (e.g. `cd /Applications/Unity/Unity.app/Contents/PlaybackEngines/MacStandaloneSupport/Variations/macosx64_nondevelopment_mono/UnityPlayer.app/Contents/MacOS`)
```
This clears away the abiguity with minimal editing to the original resources.

**Comment by boggydigital** [comment]
Great suggestion - thank you! Should be fixed with https://github.com/boggydigital/mac-gaming-guides/commit/e20bf570d090075a0a89fa287af9850d4204b020
